# Runner register
#
# sudo gitlab-runner register \
# --non-interactive \
# --leave-runner \
# --url "https://git.mp-group.net/" \
# --registration-token "<token>" \
# --executor "shell" \
# --shell "bash" \
# --description "mpsdev02.mp-group.local" \
# --run-untagged="true" \
# --tag-list "cloudbase,less,symfony,yarn" \
# --locked="false" \
# --access-level="not_protected" \
#
.git-script: &git-script |
  cd /srv/www/symfony.idno/html
  git status
  lines=$(git status -s translations | wc -l)
  if [ $lines -gt 0 ];then
    echo "committing translations"
    git config --global user.name "staging.id-no.com"
    git config --global user.email "git@mp-group.net"
    git checkout -b translations-`date +%Y%m%d-%H%M`
    git add translations/*
    git commit -m "[AUTO] Translations"
    git push --set-upstream origin -o ci.skip translations-`date +%Y%m%d-%H%M`
    git checkout staging
  else
    echo "no change, nothing to commit"
  fi


# cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - yarn


# We tell GitLab to install all the packages
# before running anything.
# Docker images come with yarn preinstalled
#before_script:
#  - apt-get update -qq && apt-get install

# You specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
  # - build
  # - test
  - staging
  - production

# staging
staging:
  stage: staging
  tags:
    - symfony

  # limit build to staging
  only:
    - staging

  except:
    - main
    - development

  # the script itself
  script:
    - cd /srv/www/symfony.idno/html

    # git
    - git checkout staging
    - git pull origin staging

    # composer
    - "/usr/bin/php8.3 /usr/local/bin/composer install --optimize-autoloader --apcu-autoloader"

    # db
    - "/usr/bin/php8.3 bin/console doctrine:migrations:migrate -q"

    # cache
    - "/usr/bin/php8.3 bin/console cache:clear"
    - "/usr/bin/php8.3 bin/console cache:warmup"

    # nvm
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
    - ". ~/.nvm/nvm.sh"
    - "nvm --version"
    - "nvm use"

    # yarn
    - yarn
    - yarn build

    # rights
    - sudo chgrp -R www-data var/cache/*
    - sudo chgrp www-data translations/*

    # finally, reload php-fpm
    - sudo systemctl reload php8.3-fpm.service


# production
production:
  stage: production
  tags:
    - symfony-prod

  # limit build to main
  only:
    - main

  except:
    - staging
    - development

  # the script itself
  script:
    - cd /srv/www/id-no.com/html

    - git checkout main
    - git pull origin main

    # composer
    - "/usr/bin/php8.3 /usr/local/bin/composer install --optimize-autoloader --apcu-autoloader"
    - /usr/bin/php8.3 /usr/local/bin/composer dump-env prod

    # db
    - "/usr/bin/php8.3 bin/console doctrine:migrations:migrate -q"

    # cache
    - "/usr/bin/php8.3 bin/console cache:clear"
    - "/usr/bin/php8.3 bin/console cache:warmup"

    # nvm
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
    - ". ~/.nvm/nvm.sh"
    - "nvm --version"
    - "nvm use --delete-prefix"

    # yarn
    - yarn
    - yarn build

  # after
  after_script:
    - cd /srv/www/id-no.com/html

    # rights
    - sudo chgrp -R www-data var/cache/
    - sudo chmod -R g+w var/cache/*

    # finally, reload php-fpm
    - sudo systemctl reload php8.3-fpm.service
    - sudo systemctl restart memcached.service

# test
#test:
#  stage: test
#  tags:
#    - cloudbase
#  script:
#    - echo "Runner test complete"

