#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# controllers:
#     resource: '../src/Controller'
#     type: annotation
#     prefix:
#         de: '/de'
#         en: '/en'


when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
